### ISSUE TITLE
Can not start in Docker

### ISSUE THREAD

**Issue by Traver-Sebi** [s-tyda/steamgifts-bot#1]
| Welcome to SteamGifts Bot!
  | Created by: github.com/s-tyda
  | Traceback (most recent call last):
  |   File "/app/cli.py", line 101, in <module>
  |     run()
  |   File "/app/cli.py", line 96, in run
  |     s = SteamGifts(**config.data)
  |   File "/usr/local/lib/python3.10/functools.py", line 970, in __get__
  |     val = self.func(instance)
  |   File "/app/cli.py", line 69, in data
  |     data = json.load(json_data_file)
  |   File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
  |     return loads(fp.read(),
  |   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
  |     return _default_decoder.decode(s)
  |   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  |   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
  |     raise JSONDecodeError("Expecting value", s, err.value) from None
  | json.decoder.JSONDecodeError: Expecting value: line 14 column 13 (char 436)

**Comment by s-tyda** [comment]
Hey, what was the problem exactly? Just wanted to know if i should change README, to not let similar issues happen in the future.

**Comment by Traver-Sebi** [comment]
It was a failure in the config.json
